apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # En base 64, postgres, SuperHiperMegaDuperTripleSecreto
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: U3VwZXJIaXBlck1lZ2FEdXBlclRyaXBsZVNlY3JldG8=